version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: fwt-postgres
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
