INSERT INTO exercise (name, description)
VALUES
('Push-up', 'A basic upper body exercise focusing on chest, shoulders, and triceps'),
('Squat', 'A compound lower-body exercise for quads, hamstrings, and glutes'),
('Lunges', 'A lower body exercise targeting the quads, hamstrings, and glutes'),
('Deadlift', 'A full-body exercise targeting the back, glutes, hamstrings, and core'),
('Bench Press', 'A chest exercise focusing on chest, shoulders, and triceps'),
('Overhead Press', 'A shoulder exercise focusing on deltoids and triceps'),
('Pull-up', 'An upper-body exercise focusing on the back, shoulders, and arms'),
('Chin-up', 'A variation of the pull-up focusing on biceps and back muscles'),
('Barbell Row', 'A back exercise targeting the lats and rhomboids'),
('Bicep Curl', 'An arm exercise focusing on the biceps'),
('Tricep Dips', 'An arm exercise focusing on the triceps'),
('Leg Press', 'A lower-body exercise targeting the quads, hamstrings, and glutes'),
('Lat Pulldown', 'A back exercise targeting the lats and shoulders'),
('Face Pull', 'A shoulder exercise focusing on rear deltoids and traps'),
('Dumbbell Fly', 'A chest exercise focusing on chest muscles'),
('Cable Fly', 'A variation of the fly focusing on chest muscles with cables'),
('Seated Row', 'A back exercise focusing on lats and rhomboids'),
('Incline Bench Press', 'A chest exercise targeting the upper chest and shoulders'),
('Decline Bench Press', 'A chest exercise targeting the lower chest and triceps'),
('Arnold Press', 'A shoulder exercise focusing on all three heads of the deltoid'),
('Hammer Curl', 'An arm exercise focusing on the biceps and brachialis'),
('Concentration Curl', 'An isolated bicep exercise for focused contraction'),
('Skull Crusher', 'A tricep exercise using a barbell or dumbbells'),
('Close-Grip Bench Press', 'A chest and triceps exercise focusing on triceps activation'),
('Sumo Deadlift', 'A deadlift variation focusing more on glutes and hamstrings'),
('Romanian Deadlift', 'A deadlift variation focusing on hamstrings and glutes'),
('Leg Curl', 'A machine exercise targeting the hamstrings'),
('Leg Extension', 'A machine exercise targeting the quads'),
('Calf Raise', 'A lower body exercise focusing on the calves'),
('Bulgarian Split Squat', 'A unilateral leg exercise focusing on quads and glutes'),
('Step-ups', 'A leg exercise focusing on quads, hamstrings, and glutes'),
('Hip Thrust', 'A glute-focused exercise using body weight or resistance'),
('Glute Bridge', 'A lower body exercise focusing on the glutes and hamstrings'),
('Pistol Squat', 'A unilateral bodyweight squat focusing on quads and glutes'),
('Box Jump', 'A plyometric leg exercise focusing on explosive strength'),
('Mountain Climbers', 'A cardio and core exercise using body weight'),
('Plank', 'A core stabilization exercise focusing on abs, back, and shoulders'),
('Side Plank', 'A variation of the plank focusing on obliques and core stability'),
('Russian Twist', 'A core exercise focusing on obliques'),
('Bicycle Crunch', 'A core exercise targeting abs and obliques'),
('Hanging Leg Raise', 'A core exercise focusing on lower abs'),
('V-Up', 'A full-body core exercise focusing on abs and hip flexors'),
('Reverse Crunch', 'A core exercise focusing on lower abs and hip flexors'),
('Flutter Kicks', 'A core exercise focusing on lower abs'),
('Superman', 'A lower-back exercise focusing on spinal erectors and glutes'),
('Bird Dog', 'A core and lower-back stabilization exercise'),
('Ab Wheel Rollout', 'A core exercise using an ab wheel to target abs and lower back'),
('Cable Crunch', 'A core exercise using cables to target the abs'),
('Tuck Jump', 'A plyometric exercise focusing on leg and core strength'),
('Burpees', 'A full-body cardio exercise combining squat, plank, and jump'),
('Jumping Jacks', 'A full-body cardio exercise using body weight'),
('High Knees', 'A cardio exercise focusing on hip flexors and quads'),
('Kettlebell Swing', 'A full-body exercise using kettlebell to target posterior chain'),
('Turkish Get-Up', 'A complex full-body exercise using a kettlebell for strength and stability'),
('Farmer’s Walk', 'A full-body exercise focusing on grip strength and core stability'),
('Renegade Row', 'A compound exercise combining plank and dumbbell rows'),
('Cable Row', 'A back exercise using cables to target lats and rhomboids'),
('Landmine Press', 'A shoulder and chest exercise using a barbell landmine attachment'),
('Landmine Squat', 'A lower-body exercise using a barbell landmine attachment'),
('Cable Lateral Raise', 'A shoulder isolation exercise focusing on deltoids'),
('Dumbbell Lateral Raise', 'A shoulder exercise focusing on the lateral head of the deltoid'),
('Dumbbell Front Raise', 'A shoulder exercise focusing on the front deltoid'),
('Rear Delt Fly', 'A shoulder exercise focusing on the posterior deltoid'),
('Shrug', 'An upper-body exercise focusing on the traps and shoulders'),
('Upright Row', 'A shoulder exercise focusing on deltoids and traps'),
('Pendlay Row', 'A back exercise focusing on lats and upper back'),
('Good Morning', 'A posterior chain exercise focusing on hamstrings and lower back'),
('Jefferson Curl', 'A flexibility and strength exercise for the spine and hamstrings'),
('Copenhagen Plank', 'A core exercise focusing on adductors and obliques'),
('Single-Leg Deadlift', 'A unilateral lower-body exercise focusing on hamstrings and balance'),
('Zercher Squat', 'A squat variation focusing on core, quads, and glutes'),
('Front Squat', 'A squat variation targeting quads and core strength'),
('Suitcase Carry', 'A unilateral full-body exercise focusing on grip and core stability');
